%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /MATLAB Drive/Exploratory Data Analysis/Final Project/StormEvents_2017_finalProject.csv
%
% Auto-generated by MATLAB on 10-Dec-2025 12:59:11

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 24);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["EpisodeID", "Event_ID", "State", "Year", "Month", "Event_Type", "CZ_Name", "Begin_Date_Time", "Timezone", "End_Date_Time", "Injuries_Direct", "Injuries_Indirect", "Deaths_Direct", "Deaths_Indirect", "Damage_Property", "Property_Cost", "Damage_Crops", "Crop_Cost", "Begin_Lat", "Begin_Lon", "End_Lat", "End_Lon", "Episode_Narrative", "Event_Narrative"];
opts.VariableTypes = ["double", "double", "categorical", "double", "categorical", "categorical", "categorical", "datetime", "double", "datetime", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "categorical", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Event_Narrative", "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["State", "Month", "Event_Type", "CZ_Name", "Episode_Narrative", "Event_Narrative"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Begin_Date_Time", "InputFormat", "yyyy-MM-dd HH:mm:ss", "DatetimeFormat", "preserveinput");
opts = setvaropts(opts, "End_Date_Time", "InputFormat", "yyyy-MM-dd HH:mm:ss", "DatetimeFormat", "preserveinput");
opts = setvaropts(opts, ["Timezone", "Damage_Property", "Damage_Crops"], "TrimNonNumeric", true);
opts = setvaropts(opts, ["Timezone", "Damage_Property", "Damage_Crops"], "ThousandsSeparator", ",");

% Import the data
StormEvents_2017_finalProject = readtable("/MATLAB Drive/Exploratory Data Analysis/Final Project/StormEvents_2017_finalProject.csv", opts);
myTable=StormEvents_2017_finalProject;

CZ_Name = myTable.CZ_Name;

% --- 2. Define the Target States ---
desiredStates = {'ARKANSAS', 'KENTUCKY', 'LOUISIANA', 'MISSISSIPPI', ...
                 'NORTH CAROLINA', 'TENNESSEE', 'TEXAS'};

% Filter rows where 'Fruit' is 'Apple'
% filteredTable = myTable(strcmp(myTable.State, 'ARKANSAS'), :);
% disp(filteredTable);

% Filter rows where 'Fruit' is "Apple" (using string comparison)
filteredTable = myTable(ismember(myTable.State, desiredStates ), :);

%Further filter the table to include only events that start between August 17th and September 3rd 
%(include the start and end dates in your analysis).
% This will give us a table of events related to << Hurricane Harvey >>.
startDate = datetime(2017, 8, 17); % Adjust year as needed
endDate = datetime(2017, 9, 3);   % Adjust year as needed

filteredTable_Month_Range = myTable(isbetween(myTable.Begin_Date_Time, startDate, endDate), :);

% Calculate the total property cost for each state to determine the states with the most damage.
% Convert the 'States' column to a categorical array for efficient grouping
StatesCat = categorical(myTable.State);
% Create a table
damage_data = table(StatesCat, myTable.Property_Cost, myTable.State, myTable.Property_Cost);

% Calculate the total property cost for each state
total_cost_by_state = groupsummary(damage_data,"StatesCat");

% Calculate the total property cost for each unique county to determine 
% the regions within the states most impacted.


%% Clear temporary variables
clear opts
