%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: /MATLAB Drive/Exploratory Data Analysis/Module 2/StormEvents_2014.csv
%
% Auto-generated by MATLAB on 05-Dec-2025 14:55:25

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 23);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["EpisodeID", "Event_ID", "State", "Year", "Month", "Event_Type", "Begin_Date_Time", "Timezone", "End_Date_Time", "Injuries_Direct", "Injuries_Indirect", "Deaths_Direct", "Deaths_Indirect", "Damage_Property", "Property_Cost", "Damage_Crops", "Crop_Cost", "Begin_Lat", "Begin_Lon", "End_Lat", "End_Lon", "Episode_Narrative", "Event_Narrative"];
opts.SelectedVariableNames = ["Event_ID", "State", "Month", "Event_Type", "Begin_Date_Time", "End_Date_Time", "Injuries_Direct", "Property_Cost", "Crop_Cost", "Begin_Lat", "Begin_Lon", "End_Lat", "End_Lon"];
opts.VariableTypes = ["string", "double", "categorical", "string", "categorical", "categorical", "datetime", "string", "datetime", "double", "string", "string", "string", "string", "double", "string", "double", "double", "double", "double", "double", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["EpisodeID", "Year", "Timezone", "Injuries_Indirect", "Deaths_Direct", "Deaths_Indirect", "Damage_Property", "Damage_Crops", "Episode_Narrative", "Event_Narrative"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["EpisodeID", "State", "Year", "Month", "Event_Type", "Timezone", "Injuries_Indirect", "Deaths_Direct", "Deaths_Indirect", "Damage_Property", "Damage_Crops", "Episode_Narrative", "Event_Narrative"], "EmptyFieldRule", "auto");
opts = setvaropts(opts, "Begin_Date_Time", "InputFormat", "yyyy-MM-dd HH:mm:ss", "DatetimeFormat", "preserveinput");
opts = setvaropts(opts, "End_Date_Time", "InputFormat", "yyyy-MM-dd HH:mm:ss", "DatetimeFormat", "preserveinput");

% Import the data
StormEvents_2014 = readtable("/MATLAB Drive/Exploratory Data Analysis/Module 2/StormEvents_2014.csv", opts);


%% Clear temporary variables
clear opts